[KlaudSol-CMS-#137] -Add pagination and page limit to tables
klaudsol/klaudsol-cms pull request #180
Opened 2023-01-28 07:36 UTC by Norlant1

1. created a customized and a reusable Pagination component `<AppContentPagination/>`. The component receives 8 required and 1 optional properties.

![1 pagination](https://user-images.githubusercontent.com/109654448/215252313-8a9a0fd1-864e-458e-bc3c-7fbbdf759757.PNG)
![1-1 pagination props](https://user-images.githubusercontent.com/109654448/215252322-e97172e9-e9e3-4218-b177-af8d503386ad.PNG)

note: default number of entries is temporarily set to 1 in the video in order to show case `next page`, `previous page`, `min page`, and `max page` functionality. The number of entries is set to 10 in PR repository.

https://user-images.githubusercontent.com/109654448/215252353-856a9fa7-c6fc-420a-b356-1d6baa7fa693.mp4

2. refactored backend queries and added limit and offset as the function parameters.

![2 refactored backend](https://user-images.githubusercontent.com/109654448/215252368-d6b77887-541e-4764-a43f-5dcdd78dfcec.PNG)

3. only show the skeleton table in the first load.

![3 skeleton](https://user-images.githubusercontent.com/109654448/215252382-ec16e747-b4e3-4feb-a25d-5c4e91233856.PNG)

4. abort all previous api request when the user moves to another page or different slug to avoid flickering of all requested datas as shown below in the video.

WITHOUT ABORT CONTROLLER

https://user-images.githubusercontent.com/109654448/215252420-b32f613e-efef-4fdf-888a-2488da118239.mp4

WITH ABORT CONTROLLER

https://user-images.githubusercontent.com/109654448/215252437-4c959405-e5fc-4668-989c-3226c1a34ee4.mp4

application of code (abort)

![4 abort](https://user-images.githubusercontent.com/109654448/215252475-6107c301-eab3-4eef-9e07-4c21f19b6a0f.PNG)

![4-2 abort](https://user-images.githubusercontent.com/109654448/215252482-67f266c6-8d89-4ee1-8558-521d9fa386cd.PNG)

5. created a separate file for const variables and reducer.

2023-01-30 14:16 UTC, Norlant1 commented
updated.

1. removed buttons' shadows

2023-02-06 04:59 UTC, angeli-mercedes commented on backend/models/core/Entity.js
> +
Kindly remove excess lines of code (Line 175 - 176)

2023-02-06 04:59 UTC, angeli-mercedes commented on backend/models/core/Entity.js
> +
Remove excess line (LIne 180)

2023-02-06 05:00 UTC, angeli-mercedes commented on backend/models/core/Entity.js
> +
Remove excess line (Line 192)

2023-02-06 05:00 UTC, angeli-mercedes commented on backend/models/core/Entity.js
> +
Remove excess line. (Lines 203 - 204)

2023-02-06 05:00 UTC, angeli-mercedes commented on backend/models/core/Entity.js
> +
Remove excess line (Line 208)

2023-02-06 05:00 UTC, angeli-mercedes commented on backend/models/core/Entity.js
> +
Remove excess line (Line 230)

2023-02-06 05:01 UTC, angeli-mercedes commented on backend/models/core/Entity.js
> +
Remove excess lines (264 - 266)

2023-02-06 05:02 UTC, angeli-mercedes commented on components/elements/inner/ContentBuilderSubMenu.js
> +  const reducer = (state, action) => {
Kindly refactor this to a separate file.

2023-02-06 05:04 UTC, angeli-mercedes commented on components/elements/inner/ContentManagerSubMenu.js
> +  const SET_SELECTED_TYPE = "SET_SELECTED_TYPE";
Kindly refactor this to a separate file.

2023-02-06 05:05 UTC, angeli-mercedes commented on components/klaudsolcms/pagination/contentPaginationVariables.js
> +export const maximumNumberOfPage = 10;
Kindly move this file to constants folder and export it to constants folder > index.js

2023-02-06 05:13 UTC, angeli-mercedes commented on components/reducers/entitiesReducer.js
> +export const SET_VALUES = "SET_VALUES";
You can refactor this to a separate file. I suggest you add this to reducers > actions.js like this

<img width="350" alt="Screenshot 2023-02-06 at 1 12 07 PM" src="https://user-images.githubusercontent.com/101687552/216888862-48d408d7-d8ca-490c-87cc-0f4253a2812a.png">

2023-02-06 05:13 UTC, angeli-mercedes commented on components/reducers/entitiesReducer.js
> +export const reducer = (state, action) => {
Kindly refactor this to a separate reducers file.

2023-02-06 05:14 UTC, angeli-mercedes reviewed
Kindly see the comments, fix the merge conflicts and assign this PR to yourself. Thanks!

2023-02-06 06:16 UTC, angeli-mercedes requested changes
Kindly address the comments.

2023-02-07 05:17 UTC, closed without merging