Fix/s3 access keys
klaudsol/klaudsol-cms pull request #220
Opened 2023-02-08 23:37 UTC by JohnServo24

Change environment variables.

(I created a branch from `main` and pulled from `staging`. There are 38 files changed, but I only changed 2 files. `S3.js` and `EntityAttributeValue.js`. But I believe that the changes on the other files are up to date.)

2023-02-08 23:52 UTC, ardeearam commented on backend/data_access/S3.js
> +const S3_SECRET_ACCESS_KEY = process.env.S3_SECRET_ACCESS_KEY;
```suggestion
//TODO: Deprecate AURORA_AWS_ACCESS_KEY_ID & AURORA_AWS_SECRET_ACCESS_KEY
const S3_ACCESS_KEY_ID = process.env.KS_S3_ACCESS_KEY_ID ??  process.env.KS_AWS_ACCESS_KEY_ID ?? process.env.AURORA_AWS_ACCESS_KEY_ID;
const S3_SECRET_ACCESS_KEY = process.env.KS_S3_SECRET_ACCESS_KEY ?? process.env.KS_AWS_SECRET_ACCESS_KEY ?? process.env.AURORA_AWS_SECRET_ACCESS_KEY;
```

2023-02-08 23:55 UTC, ardeearam commented on backend/data_access/S3.js
> +const REGION = process.env.AURORA_AWS_REGION;
```suggestion
//TODO: Deprecate AURORA_AWS_REGION on release V3.0.0
const REGION = process.env.KS_S3_REGION ?? process.env.KS_AWS_REGION ?? process.env.AURORA_AWS_REGION;
```

2023-02-08 23:57 UTC, ardeearam commented on backend/data_access/S3.js
> +const S3_BUCKET = process.env.S3_BUCKET;
```suggestion
const S3_BUCKET = process.env.KS_S3_BUCKET;
```

2023-02-08 23:59 UTC, ardeearam commented on components/EntityAttributeValue.js
> +        const bucketBaseUrl = process.env.S3_BASE_URL;
```suggestion
        const bucketBaseUrl = process.env.KS_S3_BASE_URL;
```

2023-02-08 23:59 UTC, ardeearam commented on lib/Discord.js
> +    //TODO: Deprecate DISCORD_TOKEN
```suggestion
    //TODO: Deprecate DISCORD_TOKEN in release v3.0.0
```

2023-02-09 00:00 UTC, ardeearam commented on next.config.js
> +  },
This is already removed. All succeeding environment variable changes should be placed in `amplify.yml`

```suggestion
  },
```

2023-02-09 00:01 UTC, ardeearam commented on next.config.js
> +    domains: (process.env.IMAGE_DOMAINS ?? "").split(","),
```suggestion
    domains: (process.env.KS_IMAGE_DOMAINS ?? "").split(","),
```

2023-02-09 00:03 UTC, ardeearam requested changes
Kindly see the change requests to adhere to our new environment variable naming convention.

2023-02-09 04:03 UTC, angeli-mercedes approved these changes

2023-02-09 04:04 UTC, merged